language: php
php:
  - 5.3
  - 5.4
script: phpunit -c src/app
before_script:
  - mysql -e 'create database GrabagameTests;'
  - ./deployment/project-setup.sh
branches:
  only:
    - develop
notifications:
  email:
    - chrismckinnel@gmail.com