<?php

namespace Grabagame\BookingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtRepository extends EntityRepository
{
    /**
     * @param Club     $club        Club object
     * @param integer  $courtNumber Court number
     *
     * @return Court
     */
    public function findCourtByClubAndCourtNumber($club, $courtNumber)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("
            SELECT c
            FROM GrabagameBookingBundle:Court c
            WHERE c.number = :courtNumber
            AND c.club = :club"
        );

        $query->setParameter('courtNumber', $courtNumber);
        $query->setParameter('club', $club);

        return $query->getOneOrNullResult();
    }
}