<?php

namespace Grabagame\BookingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{

    /**
     * @param Group $group
     *
     * @return array
     */
    public function findUserByGroup($group)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT m
            FROM GrabagameBookingBundle:Member m
            JOIN m.groups g WHERE g = :group
        ');
        $query->setParameter('group', $group);

        return $query->getResult();
    }    
}