#Password reset
member_forgot_password:
    pattern:  /forgot/
    defaults: { _controller: Grabagame\BookingBundle\Controller\MemberController::forgotPasswordAction }

member_reset_password_request:
    pattern:  /reset-request/
    defaults: { _controller: Grabagame\BookingBundle\Controller\MemberController::resetPasswordRequestAction }

member_reset_password:
    pattern:  /reset/{uniqueHash}/
    defaults: { _controller: Grabagame\BookingBundle\Controller\MemberController::resetPasswordFormAction }

member_submit_reset_password:
    pattern:  /submit-reset/{uniqueHash}/
    defaults: { _controller: Grabagame\BookingBundle\Controller\MemberController::submitResetPasswordAction }
