fos_user_registration_register:
    pattern: /
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_registration_check_email:
    pattern: /check-email/
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    requirements:
        _method: GET

fos_user_registration_confirm:
    pattern: /confirm/{token}/
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    requirements:
        _method: GET

fos_user_registration_confirmed:
    pattern: /confirmed/
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    requirements:
        _method: GET
