home:
    pattern:  /
    defaults: { _controller: GrabagameBookingBundle:Home:index }

about:
    pattern: /about/
    defaults: { _controller: GrabagameBookingBundle:Home:about }

submit_error_report:
    pattern: /submit_error/
    defaults: { _controller: GrabagameBookingBundle:Home:submitError }
