<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120514193451 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE grabagame_user_group (member_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_438BB43D7597D3FE (member_id), INDEX IDX_438BB43DFE54D947 (group_id), PRIMARY KEY(member_id, group_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE grabagame_user_group ADD CONSTRAINT FK_438BB43D7597D3FE FOREIGN KEY (member_id) REFERENCES member(id)");
        $this->addSql("ALTER TABLE grabagame_user_group ADD CONSTRAINT FK_438BB43DFE54D947 FOREIGN KEY (group_id) REFERENCES member_group(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE grabagame_user_group");
    }
}
