<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120514220313 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, role VARCHAR(70) NOT NULL, UNIQUE INDEX UNIQ_57698A6A57698A6A (role), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE grabagame_user_group (member_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_438BB43D7597D3FE (member_id), INDEX IDX_438BB43DFE54D947 (group_id), PRIMARY KEY(member_id, group_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE member_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_FE1D1365E237E06 (name), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE grabagame_user_group ADD CONSTRAINT FK_438BB43D7597D3FE FOREIGN KEY (member_id) REFERENCES member(id)");
        $this->addSql("ALTER TABLE grabagame_user_group ADD CONSTRAINT FK_438BB43DFE54D947 FOREIGN KEY (group_id) REFERENCES member_group(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE grabagame_user_group DROP FOREIGN KEY FK_438BB43DFE54D947");
        $this->addSql("DROP TABLE role");
        $this->addSql("DROP TABLE grabagame_user_group");
        $this->addSql("DROP TABLE member_group");
    }
}
