<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120507141133 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE booking ADD bookingOnBehalf_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED3D98E9D FOREIGN KEY (bookingOnBehalf_id) REFERENCES booking_on_behalf(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_E00CEDDED3D98E9D ON booking (bookingOnBehalf_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDED3D98E9D");
        $this->addSql("DROP INDEX UNIQ_E00CEDDED3D98E9D ON booking");
        $this->addSql("ALTER TABLE booking DROP bookingOnBehalf_id");
    }
}
