<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120507135603 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE booking_on_behalf (id INT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, club_id INT DEFAULT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_28ED725E3301C60 (booking_id), INDEX IDX_28ED725E61190A32 (club_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE booking_on_behalf ADD CONSTRAINT FK_28ED725E3301C60 FOREIGN KEY (booking_id) REFERENCES booking(id)");
        $this->addSql("ALTER TABLE booking_on_behalf ADD CONSTRAINT FK_28ED725E61190A32 FOREIGN KEY (club_id) REFERENCES club(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE booking_on_behalf");
    }
}
