<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120507161320 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE booking_on_behalf DROP FOREIGN KEY FK_28ED725E61190A32");
        $this->addSql("DROP INDEX IDX_28ED725E61190A32 ON booking_on_behalf");
        $this->addSql("ALTER TABLE booking_on_behalf DROP club_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE booking_on_behalf ADD club_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE booking_on_behalf ADD CONSTRAINT FK_28ED725E61190A32 FOREIGN KEY (club_id) REFERENCES club(id)");
        $this->addSql("CREATE INDEX IDX_28ED725E61190A32 ON booking_on_behalf (club_id)");
    }
}
