GrabagameBookingBundle:
    resource: "@GrabagameBookingBundle/Resources/config/routing/routing.yml"
    prefix: /

booking:
    resource: "@GrabagameBookingBundle/Resources/config/routing/booking.yml"
    prefix: /booking

club:
    resource: "@GrabagameBookingBundle/Resources/config/routing/admin/club.yml"
    prefix: /admin/club

group:
    resource: "@GrabagameBookingBundle/Resources/config/routing/admin/group.yml"
    prefix: /admin/group

dashboard:
    resource: "@GrabagameBookingBundle/Resources/config/routing/admin/dashboard.yml"
    prefix: /admin

member_admin:
    resource: "@GrabagameBookingBundle/Resources/config/routing/admin/member.yml"
    prefix: /admin/member

member:
    resource: "@GrabagameBookingBundle/Resources/config/routing/member.yml"
    prefix: /member

password:
    resource: "@GrabagameBookingBundle/Resources/config/routing/password.yml"
    prefix: /password

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_registration:
    resource: "@GrabagameBookingBundle/Resources/config/routing/registration.yml"
    prefix: /register

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
